### PR TITLE
Frontend Routes for Admin

### PR DESCRIPTION
**Pull request by yj-soh**
Short PR for the admin panel's routes.
They're all set to a blank page (with a TODO div) at the moment.

Are these URLs okay?
They can be changed anything, I'm just wondering if they'll conflict with the server's API.
Will we be using `/api/*` for those?

### CODE REVIEW

**Comment by ndt93** [comment]
Ideally, the `api` or `app` part should be the subdomain name, but we haven't settle this yet so you can leave them out for now.

The `/users` or `/admins` should return all paged users if not provided any parameters so we probably don't need `/users/all` etc.

The action should be reflected by the HTTP request method as much as possible instead of part of the path which is used to identify resource hierachy. So instead of `/admins/create`, it should be a HTTP request: `POST /amins'

The Search API is prioritized with its own API category (following the style of facebook and github) so searching for a user would be `/search/users` instead of `/users/search`

**Comment by yj-soh** [comment]
These are URLs for pages, not requests.
They're handled by JavaScript.

Essentially, the flow goes like this:
User goes to base home page
-> JS on page determines which "virtual page" to redirect to based on url in address
-> JS loads components and parts to render that "virtual page" into an actual one.

So, for example, if the user goes to `/app/users`, the server will serve `/app/index.htm` instead.
The JS on the page then detects that it's supposed to be `/app/users`, redirects to `/app/users/all` virtually, and renders the components for that page.
The JS in those components will then activate and send a request to `/api/users`, reorganises the retrieved data, and renders them.

So, yeah, these URLs are meant for the web browser, not for API requests.

(The `/users; /admins` redirect thing is for keeping things consistent + a way to detect the specific current page if there's any need to check.)

**Comment by ndt93** [comment]
All right, sure. Since we use the subdomain to distinguish between the app server and the media server, not the `api` and the `pages`, we should have some prefix to avoid clashes with the api. How about something like `/admins/pages/...` for admin pages and `/views/pages/..` for pages to view stream from web browser? Or maybe the other way round `/pages/...`

**Comment by yj-soh** [comment]
I personally prefer something more generic like `/admin` or `/app`.
`/admin/pages/` sounds okay. (admins sounds like a request)
It'll result in `/admin/pages/admins` for the admin CRUD pages in the admin web pages, though, lol.

`root/view` - WebView
`root/admin` - Admin Panel
`root/api` - REST API

^ Works?
(Not sure if we should still append `/pages/` after `view` and `admin`.
This affects only the user-facing URL, it's internally all represented as JS files)

I'll run with that for static file handler on the server side if that's okay.
I'll probably be leaving the static file handler for later, until we have a minimum REST API (able to connect to DB, return JSON).
I think I'll probably mess the files up if I try jamming it in somewhere now.

**Comment by ndt93** [comment]
Ok sure I will reconfigure the REST routes with /api prefix then.

**Pull request merged**
